#!/bin/bash

export PATH=$PATH:~/.local/bin

# Avoid the shell uglyness under /dev/tty type term
[ ! "$(tty | grep /dev/tty)" ] && {
  if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
  fi
}

# Establish ssh-agent if none is running
[ ! "$(ps -fe | grep ssh-agent | grep -v grep)" ] && {
  eval $(ssh-agent -s)
  ssh-add
}

[[ $TERM_PROGRAM ]] && {
  [[ $TERM_PROGRAM = "vscode" ]] && {
    exit
  }
}


SESSION=$(whoami)

SESSIONS=$(tmux list-sessions | grep $SESSION)

[[ "$SESSIONS" =~ "no server running" ]] && {
  SESSIONS=""
}
[[ "$SESSIONS" = "" ]] && {
  [[ ! "$(uname -a)" =~ "microsoft-standard" ]] && {
    systemd-run --scope --user tmux new-session -d -s $SESSION
  } || {
    tmux new-session -d -s $SESSION
    tmux set -g update-environment "SSH_AUTH_SOCK SSH_CONNECTION SSH_CLIENT SSH_TTY"
  }
  tmux rename-window -t $SESSION:0 'Chat'
  tmux send -t $SESSION:0 'TERM=tmux-256color ls' 'ENTER'
  tmux new-window -t $SESSION:1 -n 'Main'
  tmux new-window -t $SESSION:2 -n 'Code'
  tmux select-window -t $SESSION:0
}

[[ ! "$TMUX" ]] && {
  tmux attach-session -t $SESSION:0
}
